version: '3.8'

services:
  api-gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - USER_SERVICE_TIMEOUT=5000
      - PRODUCT_SERVICE_TIMEOUT=5000
      - USER_SERVICE_RETRIES=3
      - PRODUCT_SERVICE_RETRIES=3
    depends_on:
      - user-service
      - product-service
    networks:
      - microservices-network
    restart: unless-stopped

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - microservices-network
    restart: unless-stopped

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  user-data:
  product-data:
